# ===== Perfil de PRODUCCION (Render) para ms-vehicle =====

spring.application.name=ms-vehicle

# BD compartida FreeSQLDatabase (Opcion B: separacion logica por tablas)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ===== Eureka en la nube =====
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443
eureka.instance.non-secure-port-enabled=false
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${RENDER_EXTERNAL_HOSTNAME}
eureka.instance.status-page-url=https://${RENDER_EXTERNAL_HOSTNAME}/actuator/info
eureka.instance.health-check-url=https://${RENDER_EXTERNAL_HOSTNAME}/actuator/health
eureka.instance.home-page-url=https://${RENDER_EXTERNAL_HOSTNAME}/

springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
