# Render

spring.application.name=ms-payment

# BD FreeSQLDatabase
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Pool de conexiones limitado FreeSQLDatabase
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:none}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=com.pe.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443
eureka.instance.non-secure-port-enabled=false
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${RENDER_EXTERNAL_HOSTNAME}
eureka.instance.status-page-url=https://${RENDER_EXTERNAL_HOSTNAME}/actuator/info
eureka.instance.health-check-url=https://${RENDER_EXTERNAL_HOSTNAME}/actuator/health
eureka.instance.home-page-url=https://${RENDER_EXTERNAL_HOSTNAME}/

springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
