# Configuracion centralizada de ms-iam (servida por Config Server)
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_iam?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "12345678"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
